### ISSUE TITLE
Todos los ELSE de todos los eventos deshabilitados

### ISSUE THREAD

**Issue by Kamusvalenzuela** [Kamusvalenzuela/InmortalUpdates#8]
Desde la última update del motor, se aplicó la nueva característica que nos permite usar de forma opcional las excepciones
Para que un evento tenga o no un "Else" habilitado
Lamentablemente con la implementación de este código nuevo
**TODOS LOS EVENTOS** perdieron su función ELSE y deben ser habilitados manualmente

- [x] Habilitados en un 25%

- [x] Habilitados en un 50%

- [x] Habilitados en un 75%

- [x] Habilitados en un 100%
